dependencies:
  - python=3 
  - pip: 
    - spacy 
    - ipykernel 
    - scipy 
    - numpy 
    - scikit-learn 
    - matplotlib 
    - pandas 
    - thinc
    - scipy
    - beautifulsoup4
    - webdriver
    - lxml
    - html5lib
